name: Node Continous Integration
on: push
jobs:
  build-node:
    name: Build Node
    runs-on: ubuntu-latest
    container: node:23.1.0
    steps: 
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v4
      - run: dir